version: '3.8'

services:
  listenarr:
    image: ghcr.io/therobbiedavis/listenarr:canary ## For Docker Hub, replace the image with docker.io/therobbiedavis/listenarr:canary
    user: "1001:1001"  ## Replace with your desired UID and GID
    ports:
      - "5000:5000"
    environment:
      - LISTENARR_PUBLIC_URL=https://your-domain.com ## OPTIONAL: Used by Discord Bot
    volumes:
      - listenarr_data:/app/config
    restart: unless-stopped

volumes:
  listenarr_data:
